type .\test\in\basic\basic_testcase01.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase01.out
type .\test\in\basic\basic_testcase02.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase02.out
type .\test\in\basic\basic_testcase03.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase03.out
type .\test\in\basic\basic_testcase04.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase04.out
type .\test\in\basic\basic_testcase05.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase05.out
type .\test\in\basic\basic_testcase06.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase06.out
type .\test\in\basic\basic_testcase07.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase07.out
type .\test\in\basic\basic_testcase08.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase08.out
type .\test\in\basic\basic_testcase09.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase09.out
type .\test\in\basic\basic_testcase10.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase10.out
type .\test\in\basic\basic_testcase11.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase11.out
type .\test\in\basic\basic_testcase12.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase12.out
type .\test\in\basic\basic_testcase13.in | c:\Users\cr17ou\AppData\Local\Programs\Python\Python311\python.exe findPalindromForCheck.py > .\test\out\basic\basic_testcase13.out
